name: relaxator
grade: stable
adopt-info: relaxator
license: GPL-3.0+

base: core20
confinement: strict

apps:
  relaxator:
    command: usr/bin/com.github.alexkdeveloper.relaxator
    extensions: [gnome-3-38]
    plugs:
      - home
    slots:
      - dbus-daemon
    common-id: com.github.alexkdeveloper.relaxator

parts:
  relaxator:
    plugin: meson
    source: https://github.com/alexkdeveloper/relaxator.git
    source-branch: main
    meson-parameters: [--prefix=/snap/relaxator/current/usr]
    build-packages:
      - libgstreamer1.0-dev
      - gettext
    organize:
      snap/relaxator/current/usr: usr
    parse-info: [usr/share/appdata/com.github.alexkdeveloper.relaxator.appdata.xml]

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.alexkdeveloper.relaxator
